#include "ui/icons.h"
#include "dprintf.h"
#include <gsKit.h>
#include <gsToolkit.h>
#include <malloc.h>
#include <png.h>
#include <stdio.h>
#include <stdlib.h>

// Embedded icon data (generated by bin2c in embed.cmake)
extern unsigned char icon_circle[] __attribute__((aligned(16)));
extern unsigned int size_icon_circle;
extern unsigned char icon_cross[] __attribute__((aligned(16)));
extern unsigned int size_icon_cross;
extern unsigned char icon_square[] __attribute__((aligned(16)));
extern unsigned int size_icon_square;
extern unsigned char icon_triangle[] __attribute__((aligned(16)));
extern unsigned int size_icon_triangle;
extern unsigned char icon_L1[] __attribute__((aligned(16)));
extern unsigned int size_icon_L1;
extern unsigned char icon_R1[] __attribute__((aligned(16)));
extern unsigned int size_icon_R1;
extern unsigned char icon_select[] __attribute__((aligned(16)));
extern unsigned int size_icon_select;
extern unsigned char icon_start[] __attribute__((aligned(16)));
extern unsigned int size_icon_start;

static GSTEXTURE *iconTextures[ICON_COUNT];

// Loads PNG from memory into GSTEXTURE and uploads to GS VRAM.
// Supports 8-bit palettized (icons) and 32-bit RGBA (e.g. splash logo); logic from gui_graphics.c gsKit_texture_png_mem.
int loadPngFromMemory(GSGLOBAL *gs, GSTEXTURE *texture, void *buf, size_t size) {
  FILE *file = fmemopen(buf, size, "rb");
  if (!file) {
    DPRINTF("ui/icons: fmemopen failed\n");
    return -1;
  }

  png_structp png_ptr = png_create_read_struct(PNG_LIBPNG_VER_STRING, NULL, NULL, NULL);
  if (!png_ptr) {
    fclose(file);
    return -1;
  }
  png_infop info_ptr = png_create_info_struct(png_ptr);
  if (!info_ptr) {
    png_destroy_read_struct(&png_ptr, NULL, NULL);
    fclose(file);
    return -1;
  }
  if (setjmp(png_jmpbuf(png_ptr))) {
    png_destroy_read_struct(&png_ptr, &info_ptr, NULL);
    fclose(file);
    return -1;
  }

  png_init_io(png_ptr, file);
  png_set_sig_bytes(png_ptr, 0);
  png_read_info(png_ptr, info_ptr);

  png_uint_32 width, height;
  int bit_depth, color_type, interlace_type;
  png_get_IHDR(png_ptr, info_ptr, &width, &height, &bit_depth, &color_type, &interlace_type, NULL, NULL);

  texture->Width = width;
  texture->Height = height;
  texture->VramClut = 0;
  texture->Clut = NULL;
  texture->PSM = GS_PSM_CT32;
  texture->Filter = GS_FILTER_NEAREST;

  if (color_type == PNG_COLOR_TYPE_RGB_ALPHA) {
    // 32-bit RGBA path (from gui_graphics.c gsKit_texture_png_mem)
    if (bit_depth == 16)
      png_set_strip_16(png_ptr);
    if (png_get_valid(png_ptr, info_ptr, PNG_INFO_tRNS))
      png_set_tRNS_to_alpha(png_ptr);
    png_set_filler(png_ptr, 0xff, PNG_FILLER_AFTER);
    png_read_update_info(png_ptr, info_ptr);

    texture->Mem = memalign(128, gsKit_texture_size(width, height, texture->PSM));
    if (!texture->Mem) {
      png_destroy_read_struct(&png_ptr, &info_ptr, NULL);
      fclose(file);
      return -1;
    }

    int row_bytes = png_get_rowbytes(png_ptr, info_ptr);
    png_bytep *row_pointers = calloc(height, sizeof(png_bytep));
    if (!row_pointers) {
      free(texture->Mem);
      texture->Mem = NULL;
      png_destroy_read_struct(&png_ptr, &info_ptr, NULL);
      fclose(file);
      return -1;
    }
    for (png_uint_32 row = 0; row < height; row++)
      row_pointers[row] = malloc(row_bytes);
    png_read_image(png_ptr, row_pointers);

    struct pixel {
      uint8_t r, g, b, a;
    };
    struct pixel *pixels = (struct pixel *)texture->Mem;
    int k = 0;
    for (png_uint_32 i = 0; i < height; i++) {
      for (png_uint_32 j = 0; j < width; j++) {
        pixels[k].r = row_pointers[i][4 * j];
        pixels[k].g = row_pointers[i][4 * j + 1];
        pixels[k].b = row_pointers[i][4 * j + 2];
        pixels[k].a = (uint8_t)((int)row_pointers[i][4 * j + 3] * 128 / 255);
        k++;
      }
    }

    for (png_uint_32 row = 0; row < height; row++)
      free(row_pointers[row]);
    free(row_pointers);
  } else if (color_type == PNG_COLOR_TYPE_PALETTE && bit_depth == 8) {
    // 8-bit palettized path
    png_colorp palette = NULL;
    int num_palette = 0;
    png_bytep trans = NULL;
    int num_trans = 0;
    if (!png_get_PLTE(png_ptr, info_ptr, &palette, &num_palette) || num_palette <= 0) {
      DPRINTF("ui/icons: missing or empty PLTE\n");
      png_destroy_read_struct(&png_ptr, &info_ptr, NULL);
      fclose(file);
      return -1;
    }
    png_get_tRNS(png_ptr, info_ptr, &trans, &num_trans, NULL);

    texture->Mem = memalign(128, gsKit_texture_size(width, height, texture->PSM));
    if (!texture->Mem) {
      png_destroy_read_struct(&png_ptr, &info_ptr, NULL);
      fclose(file);
      return -1;
    }

    int row_bytes = png_get_rowbytes(png_ptr, info_ptr);
    png_bytep *row_pointers = calloc(height, sizeof(png_bytep));
    if (!row_pointers) {
      free(texture->Mem);
      texture->Mem = NULL;
      png_destroy_read_struct(&png_ptr, &info_ptr, NULL);
      fclose(file);
      return -1;
    }
    for (png_uint_32 row = 0; row < height; row++)
      row_pointers[row] = malloc(row_bytes);
    png_read_image(png_ptr, row_pointers);

    struct pixel {
      uint8_t r, g, b, a;
    };
    struct pixel *pixels = (struct pixel *)texture->Mem;
    for (png_uint_32 i = 0; i < height; i++) {
      png_bytep row = row_pointers[i];
      for (png_uint_32 j = 0; j < width; j++) {
        int idx = row[j];
        pixels->r = idx < num_palette ? palette[idx].red : 0;
        pixels->g = idx < num_palette ? palette[idx].green : 0;
        pixels->b = idx < num_palette ? palette[idx].blue : 0;
        if (idx < num_trans)
          pixels->a = (uint8_t)((int)trans[idx] * 128 / 255);
        else
          pixels->a = 0;
        pixels++;
      }
    }

    for (png_uint_32 row = 0; row < height; row++)
      free(row_pointers[row]);
    free(row_pointers);
  } else {
    DPRINTF("ui/icons: only 8-bit palettized or 32-bit RGBA PNG supported\n");
    png_destroy_read_struct(&png_ptr, &info_ptr, NULL);
    fclose(file);
    return -1;
  }

  png_read_end(png_ptr, NULL);
  png_destroy_read_struct(&png_ptr, &info_ptr, NULL);
  fclose(file);

  gsKit_TexManager_bind(gs, texture);
  return 0;
}

static void freeIcon(GSTEXTURE *t) {
  if (!t)
    return;
  if (t->Mem) {
    free(t->Mem);
    t->Mem = NULL;
  }
  free(t);
}

int initIconsOnly(GSGLOBAL *gs) {
  for (int i = 0; i < ICON_COUNT; i++) {
    if (iconTextures[i]) {
      freeIcon(iconTextures[i]);
      iconTextures[i] = NULL;
    }
  }

  struct {
    const void *data;
    size_t size;
  } assets[] = {
      {icon_circle, size_icon_circle},     {icon_cross, size_icon_cross}, {icon_square, size_icon_square},
      {icon_triangle, size_icon_triangle}, {icon_L1, size_icon_L1},       {icon_R1, size_icon_R1},
      {icon_select, size_icon_select},     {icon_start, size_icon_start}, {NULL, 0},
  };

  for (int i = 0; i < ICON_COUNT; i++) {
    if (!assets[i].data || assets[i].size == 0)
      continue;
    GSTEXTURE *t = calloc(1, sizeof(GSTEXTURE));
    if (!t)
      continue;
    if (loadPngFromMemory(gs, t, (void *)assets[i].data, assets[i].size) != 0) {
      free(t);
      continue;
    }
    t->Filter = GS_FILTER_LINEAR;
    iconTextures[i] = t;
  }
  return 0;
}

void drawIconAt(GSGLOBAL *gs, float x, float y, float w, float h, int z, uint64_t color, IconType iconType) {
  if (iconType < 0 || iconType >= ICON_COUNT || !iconTextures[iconType])
    return;
  GSTEXTURE *t = iconTextures[iconType];
  gsKit_TexManager_bind(gs, t);
  gsKit_prim_sprite_texture(gs, t, x, y, 0.f, 0.f, x + w, y + h, (float)t->Width, (float)t->Height, z, color);
}

int getIconWidth(IconType iconType) {
  if (iconType < 0 || iconType >= ICON_COUNT || !iconTextures[iconType])
    return 0;
  return iconTextures[iconType]->Width;
}

int getIconHeight(IconType iconType) {
  if (iconType < 0 || iconType >= ICON_COUNT || !iconTextures[iconType])
    return 0;
  return iconTextures[iconType]->Height;
}
