#include "ui/icons.h"
#include "dprintf.h"
#include "ui/png.h"
#include <gsKit.h>
#include <gsToolkit.h>
#include <malloc.h>
#include <png.h>
#include <stdio.h>
#include <stdlib.h>

// Macros for loading embedded IOP modules
#define ICON_DEFINE(name)                                                                                                                            \
  extern unsigned char icon_##name[] __attribute__((aligned(16)));                                                                                   \
  extern uint32_t size_icon_##name

// Macros for loading embedded IOP modules
#define ASSET_DEFINE(name) {icon_##name, size_icon_##name}

// Embedded icon data (generated by bin2c in embed.cmake)
ICON_DEFINE(circle);
ICON_DEFINE(cross);
ICON_DEFINE(square);
ICON_DEFINE(triangle);
ICON_DEFINE(L1);
ICON_DEFINE(R1);
ICON_DEFINE(select);
ICON_DEFINE(start);

static GSTEXTURE *iconTextures[ICON_COUNT];

static void freeIcon(GSTEXTURE *t) {
  if (!t)
    return;
  if (t->Mem) {
    free(t->Mem);
    t->Mem = NULL;
  }
  if (t->Clut) {
    free(t->Clut);
    t->Clut = NULL;
  }
  free(t);
}

int initIcons(GSGLOBAL *gs) {
  for (int i = 0; i < ICON_COUNT; i++) {
    if (iconTextures[i]) {
      freeIcon(iconTextures[i]);
      iconTextures[i] = NULL;
    }
  }

  struct {
    const void *data;
    size_t size;
  } assets[] = {
      ASSET_DEFINE(circle),   ASSET_DEFINE(cross), ASSET_DEFINE(square),
      ASSET_DEFINE(triangle), ASSET_DEFINE(L1),    ASSET_DEFINE(R1),
      ASSET_DEFINE(select),   ASSET_DEFINE(start), {NULL, 0},
  };

  for (int i = 0; i < ICON_COUNT; i++) {
    if (!assets[i].data || assets[i].size == 0)
      continue;
    GSTEXTURE *t = calloc(1, sizeof(GSTEXTURE));
    if (!t)
      continue;
    if (loadPNGFromMemory(gs, t, (void *)assets[i].data, assets[i].size) != 0) {
      free(t);
      continue;
    }
    t->Filter = GS_FILTER_LINEAR;
    iconTextures[i] = t;
  }
  return 0;
}

void drawIconAt(GSGLOBAL *gs, float x, float y, float w, float h, int z, uint64_t color, IconType iconType) {
  if (iconType < 0 || iconType >= ICON_COUNT || !iconTextures[iconType])
    return;
  GSTEXTURE *t = iconTextures[iconType];
  gsKit_TexManager_bind(gs, t);
  gsKit_prim_sprite_texture(gs, t, x, y, 0.f, 0.f, x + w, y + h, (float)t->Width+1, (float)t->Height+1, z, color);
}

int getIconWidth(IconType iconType) {
  if (iconType < 0 || iconType >= ICON_COUNT || !iconTextures[iconType])
    return 0;
  return iconTextures[iconType]->Width;
}

int getIconHeight(IconType iconType) {
  if (iconType < 0 || iconType >= ICON_COUNT || !iconTextures[iconType])
    return 0;
  return iconTextures[iconType]->Height;
}
